name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Select Xcode version # Xcode 11.2 を使う
      run: sudo xcode-select -s '/Applications/Xcode_12.2.app/Contents/Developer'
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
